version: "1"

services:
- type: web
  name: Homely
  runtime: docker
  repo: https://github.com/BelfDev/homely
  plan: free
  envVars:
  - key: POSTGRES_PASSWORD
    sync: false
  - key: POSTGRES_USER
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: HOMELY_SECRET
    sync: false
  - key: FLASK_ENV
    sync: false
  - key: FLASK_APP
    sync: false
  - key: JWT_SECRET_KEY
    sync: false
  - key: JWT_ACCESS_TOKEN_EXPIRES
    sync: false
  region: frankfurt
  healthCheckPath: /api/v1/health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeploy: false
  rootDir: backend/api

# Exported from Render on 2024-10-10T07:55:33Z
databases:
  - name: homely-db
    databaseName: homely_e0bt
    user: homely_e0bt_user
    plan: basic-256mb
    region: frankfurt
    ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere
    postgresMajorVersion: "16"
    diskSizeGB: 1
