version: "1"

services:
- type: web
  name: Homely
  runtime: docker
  repo: https://github.com/BelfDev/homely
  plan: free
  envVars:
  - key: POSTGRES_PASSWORD
    sync: false
  - key: POSTGRES_USER
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: HOMELY_SECRET
    sync: false
  - key: FLASK_ENV
    sync: false
  - key: FLASK_APP
    sync: false
  - key: JWT_SECRET_KEY
    sync: false
  region: frankfurt
  healthCheckPath: /api/v1/health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeploy: false
  rootDir: backend/api

databases:
- name: homely-db
  databaseName: homely_e0bt
  user: homely_e0bt_user
  plan: starter
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
