# Every Render Blueprint is backed by a YAML file that defines a set of interconnected services, databases, and environment groups.
services:
  - type: web
    name: homely-web
    plan: free
    repo: https://github.com/BelfDev/homely.git
    branch: main
    rootDir: backend/api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: ""
    healthCheckPath: /api/v1/health
    autoDeploy: true
    region: frankfurt
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src
      - key: HOMELY_SECRET
        sync: true
      - key: JWT_SECRET_KEY
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: homely-db
          property: connectionString

databases:
  - name: homely-db
    postgresMajorVersion: "13"
    region: frankfurt 
    plan: free 
    databaseName: homely
    user: postgres
    