openapi: 3.0.3
info:
  title: Homely API
  version: 1.0.0
  description: "A simple home automation API"
servers:
  - url: http://127.0.0.1:5000/api
    description: Development server
  - url: https://homely-uabv.onrender.com/api
    description: Production server
paths:
  /v1/health:
    get:
      summary: Health check
      responses:
        '200':
          description: Health check status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /v1/users:
    get:
      summary: Get list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user and log them in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created successfully and logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  accessToken:
                    type: string
                    description: JWT access token for the new user
        '400':
          description: Bad request (e.g., invalid data or email already exists)
  /v1/users/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token for authenticated requests
        '400':
          description: Invalid request (e.g., missing or invalid email/password)
        '401':
          description: Unauthorized (incorrect credentials)
  /v1/admin/users:
    get:
      summary: Get all users (admin)
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /v1/users/me:
    get:
      summary: Get current logged-in user
      responses:
        '200':
          description: Current user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    UserCreate:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          