name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Step 3: Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: |
          docker build -t homely-api-image:latest -f backend/api/Dockerfile backend/api

      # Step 4: Run auto-formatting check with black
      - name: Check code formatting with black
        run: |
          docker run homely-api-image:latest poetry run black --check ./api

      # Step 5: Run linter inside Docker container (flake8)
      - name: Run flake8 linter
        run: |
          docker run homely-api-image:latest poetry run flake8 ./api

      # Step 6: Run tests inside the Docker container
      - name: Run tests inside Docker container
        run: |
          docker run homely-api-image:latest poetry run pytest --maxfail=1 --disable-warnings
