"""Simplify task model

Revision ID: 9dacb9f9474f
Revises: d283caef7445
Create Date: 2024-11-02 21:48:10.707114

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9dacb9f9474f"
down_revision = "d283caef7445"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("start_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("end_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.drop_column("start_time")
        batch_op.drop_column("end_time")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "end_time",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "start_time",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("end_at")
        batch_op.drop_column("start_at")

    # ### end Alembic commands ###
