"""Introduce task-user relationship

Revision ID: d283caef7445
Revises: 55f2c113c1e0
Create Date: 2024-11-01 10:07:45.298242

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d283caef7445"
down_revision = "55f2c113c1e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_assignees", schema=None) as batch_op:
        batch_op.drop_column("id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_assignees", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.UUID(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
